# Generated by Django 3.2.13 on 2024-06-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_id_public',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
