# Generated by Django 3.2.13 on 2024-06-28 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_shop_shop_id_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shop',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
