# Generated by Django 3.2.13 on 2024-06-28 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20240628_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('serial_no', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=255)),
                ('shopid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(null=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shop')),
            ],
        ),
    ]
