# Generated by Django 3.2.13 on 2024-06-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_logo',
            field=models.ImageField(null=True, upload_to='shop_resources/logo/'),
        ),
    ]
